[workspace]

resolver = "2"

members = [
  "abc430",
  "abc431",
  "abc432",
  "arc210",
  "abc433",
  "abc434",
  "arc211",
  "abc435",
  "abc436",
  "abc437",
  "abc438",
  "abc439",
  "abc440",
  "arc212",
  "abc441",
  "abc442",
  "abc443",
  "abc444",
  "abc445",
  "arc215",
  "abc447",
  "abc448",
  "abc451",
  "abc452",
  "abc453",
  "abc456",
  "arc218",
  "abc457",
  "arc219",
  "abc458",
]
